### ISSUE TITLE
Error while uploading multiple images (Mx SP9.1.0)

### ISSUE THREAD

**Issue by Criccle** [JelteMX/mendix-file-dropper#19]
Hi! Love this widget, but unfortunately ran into an issue while uploading multiple images. I get the following stacktrace message.  Uploading one by one works fine.

```
com.mendix.core.CoreRuntimeException: Failed to commit
	at com.mendix.basis.component.TransactionCore.commit(TransactionCore.scala:151)

Caused by: com.mendix.core.CoreRuntimeException: com.mendix.systemwideinterfaces.MendixRuntimeException: com.mendix.core.CoreRuntimeException: Exception occurred in action '{"type":"CommitAction"}', all database changes executed by this action were rolled back
	at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:84)

Caused by: com.mendix.systemwideinterfaces.MendixRuntimeException: com.mendix.core.CoreRuntimeException: Exception occurred in action '{"type":"CommitAction"}', all database changes executed by this action were rolled back
	at com.mendix.util.classloading.Runner.withContextClassLoader(Runner.java:23)

Caused by: com.mendix.core.CoreRuntimeException: Exception occurred in action '{"type":"CommitAction"}', all database changes executed by this action were rolled back
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.processErrorState(CoreActionHandlerImpl.scala:150)

Caused by: com.mendix.systemwideinterfaces.connectionbus.data.UniqueConstraintViolationRuntimeException: Duplicate column value violates its unique constraint: ERROR: duplicate key value violates unique constraint "melding$melding_pkey"
  Detail: Key (id)=(36591746972387284) already exists. (SQL State: 23505, Error Code: 0)
```

**Comment by Criccle** [comment]
Addition to the above comment: This was on the New page of a new object. When I put the File Dropper widget in a popup, this behavior disappears and uploading multiple images works just fine. For me this is a well enough workaround so I'll close the issue again!
